import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { GET_POKEMON } from '../queries/pokeQuery';
import { useSelector } from 'react-redux';
import { useQuery } from '@apollo/client';

const Home: NextPage = () => {
  const { email, password, username } = useSelector((state: any) => state.user);
  const [loggedIn, setLoggedIn] = useState(false);

  const [emailInput, setEmailInput] = useState('');
  const [passwordInput, setPasswordInput] = useState('');

  const checkInput = () => {
    if (emailInput === email && passwordInput === password) {
      setLoggedIn(true);
    }
  };

  const QueryPokemon = 'blastoise';

  const { loading, error, data } = useQuery(GET_POKEMON, {
    variables: {
      getPokemonId: QueryPokemon,
    },
  });

  return (
    <div>
      <Head>
        <title>Pokemon API with Redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!loggedIn ? (
        <main className="h-screen w-full flex items-center justify-center">
          <div className="border border-gray-200 w-1/3 h-1/4 flex flex-col justify-center">
            <h1 className="text-center font-semibold text-2xl">Poke API</h1>
            <p className="text-center text-gray-600 mt-1 underline">
              Login to your account
            </p>
            <div className="text-center py-2">
              <p className="mr-2">Email:</p>
              <input
                className="border"
                onChange={(e) => setEmailInput(e.target.value)}
              ></input>
              <p className="mr-2">Password:</p>
              <input
                className="border"
                onChange={(e) => setPasswordInput(e.target.value)}
              ></input>
            </div>
            <button
              className="border border-blue-400 w-fit px-10 mx-auto mt-2"
              onClick={(e) => {
                e.preventDefault();
                checkInput();
              }}
            >
              Login
            </button>
          </div>
        </main>
      ) : (
        <div className="h-screen flex flex-col items-center justify-center">
          <p>Hello, {username}</p>
          {loading ? (
            <p>Loading data...</p>
          ) : (
            <div>
              <p>Name: {data.getPokemon.name}</p>
              <img src={data.getPokemon.sprites?.front_default}></img>
              <p>Type: {data.getPokemon.types[0].type.name}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default Home;
